/* TOEIC 高分学习助手 - 词库数据 */
/* eslint-disable */
"use strict";

/* 每个分类: {id, name, icon, words: [{w:单词, p:词性, zh:中文, ex:例句}]} */
const VOCAB_DATA = [
  {
    id: "office", name: "办公室", icon: "🏢",
    words: [
      { w: "agenda", p: "n.", zh: "议程；议事日程", ex: "Please add this topic to the meeting agenda." },
      { w: "minutes", p: "n.", zh: "会议记录", ex: "She is taking the minutes of the meeting." },
      { w: "memo", p: "n.", zh: "备忘录；内部通知", ex: "The manager sent a memo to all staff." },
      { w: "deadline", p: "n.", zh: "截止日期", ex: "The deadline for the report is Friday." },
      { w: "colleague", p: "n.", zh: "同事", ex: "My colleagues are friendly and helpful." },
      { w: "supervisor", p: "n.", zh: "主管；上司", ex: "Ask your supervisor for approval." },
      { w: "department", p: "n.", zh: "部门", ex: "He works in the sales department." },
      { w: "conference room", p: "n.", zh: "会议室", ex: "The conference room is booked at 3 p.m." },
      { w: "schedule", p: "n./v.", zh: "日程；安排", ex: "Let's schedule the meeting for Monday." },
      { w: "appointment", p: "n.", zh: "预约；约定", ex: "I have an appointment with the dentist." },
      { w: "extension", p: "n.", zh: "分机（号）", ex: "What is your phone extension?" },
      { w: "stationery", p: "n.", zh: "文具", ex: "Order more stationery for the office." },
      { w: "photocopy", p: "n./v.", zh: "复印；复印件", ex: "Can you photocopy this contract?" },
      { w: "printer", p: "n.", zh: "打印机", ex: "The printer is out of paper." },
      { w: "projector", p: "n.", zh: "投影仪", ex: "Set up the projector for the presentation." },
      { w: "assignment", p: "n.", zh: "任务；分配的工作", ex: "Finish the assignment by tomorrow." },
      { w: "notice board", p: "n.", zh: "布告栏", ex: "Check the notice board for updates." },
      { w: "workload", p: "n.", zh: "工作量", ex: "My workload is heavy this month." },
      { w: "overtime", p: "n.", zh: "加班", ex: "He works overtime twice a week." },
      { w: "relocate", p: "v.", zh: "搬迁；调动", ex: "The company will relocate to a new building." }
    ]
  },
  {
    id: "business", name: "会议与商务", icon: "🤝",
    words: [
      { w: "negotiate", p: "v.", zh: "谈判；协商", ex: "We plan to negotiate a lower price." },
      { w: "contract", p: "n.", zh: "合同", ex: "Sign the contract before the end of the month." },
      { w: "proposal", p: "n.", zh: "提案；建议书", ex: "The client rejected our proposal." },
      { w: "client", p: "n.", zh: "客户", ex: "The client requested a revised design." },
      { w: "vendor", p: "n.", zh: "供应商", ex: "Choose a vendor with good reviews." },
      { w: "partnership", p: "n.", zh: "合作关系", ex: "The two firms formed a partnership." },
      { w: "merger", p: "n.", zh: "合并", ex: "The merger will be completed next year." },
      { w: "budget", p: "n.", zh: "预算", ex: "We exceeded our travel budget." },
      { w: "revenue", p: "n.", zh: "营业收入", ex: "Revenue rose by 15 percent this quarter." },
      { w: "profit", p: "n.", zh: "利润", ex: "The company doubled its profits." },
      { w: "expense", p: "n.", zh: "费用；开支", ex: "Keep all receipts for business expenses." },
      { w: "invoice", p: "n.", zh: "发票；账单", ex: "The invoice was sent on Monday." },
      { w: "quotation", p: "n.", zh: "报价单", ex: "Request a quotation from three vendors." },
      { w: "stakeholder", p: "n.", zh: "利益相关方", ex: "Present the plan to the stakeholders." },
      { w: "presentation", p: "n.", zh: "演示；报告", ex: "His presentation was well organized." },
      { w: "consensus", p: "n.", zh: "共识", ex: "The board finally reached a consensus." },
      { w: "implement", p: "v.", zh: "实施；执行", ex: "Implement the new policy in April." },
      { w: "evaluate", p: "v.", zh: "评估", ex: "We will evaluate the results next week." },
      { w: "collaborate", p: "v.", zh: "合作", ex: "The two teams collaborated on the project." },
      { w: "objective", p: "n.", zh: "目标", ex: "Set clear objectives for the team." }
    ]
  },
  {
    id: "hr", name: "人事招聘", icon: "👥",
    words: [
      { w: "recruit", p: "v.", zh: "招聘", ex: "The firm plans to recruit 50 engineers." },
      { w: "applicant", p: "n.", zh: "申请者", ex: "Over 100 applicants applied for the post." },
      { w: "resume", p: "n.", zh: "简历", ex: "Attach your resume to the application." },
      { w: "interview", p: "n./v.", zh: "面试", ex: "She has a job interview tomorrow." },
      { w: "hire", p: "v.", zh: "雇用", ex: "We hired two new designers." },
      { w: "resign", p: "v.", zh: "辞职", ex: "He resigned after ten years." },
      { w: "promote", p: "v.", zh: "晋升；提拔", ex: "She was promoted to manager." },
      { w: "salary", p: "n.", zh: "薪水（月/年薪）", ex: "The salary is negotiable." },
      { w: "wage", p: "n.", zh: "工资（时/周薪）", ex: "The minimum wage will rise next year." },
      { w: "bonus", p: "n.", zh: "奖金", ex: "Employees get a yearly bonus." },
      { w: "benefit", p: "n.", zh: "福利", ex: "Health insurance is a standard benefit." },
      { w: "pension", p: "n.", zh: "养老金", ex: "He retired with a good pension." },
      { w: "training", p: "n.", zh: "培训", ex: "New staff receive two weeks of training." },
      { w: "workshop", p: "n.", zh: "研讨会；工作坊", ex: "Attend the leadership workshop on Friday." },
      { w: "evaluation", p: "n.", zh: "绩效评估", ex: "My annual evaluation is next month." },
      { w: "transfer", p: "n./v.", zh: "调动；转岗", ex: "He was transferred to the Osaka office." },
      { w: "vacancy", p: "n.", zh: "空缺职位", ex: "There is a vacancy in the IT team." },
      { w: "reference", p: "n.", zh: "推荐信；介绍人", ex: "List two references on your resume." },
      { w: "probation", p: "n.", zh: "试用期", ex: "Probation lasts three months." },
      { w: "layoff", p: "n.", zh: "裁员", ex: "The factory announced layoffs." }
    ]
  },
  {
    id: "finance", name: "财务金融", icon: "💰",
    words: [
      { w: "deposit", p: "n./v.", zh: "存款；押金", ex: "Pay a deposit to reserve the room." },
      { w: "withdraw", p: "v.", zh: "取款；撤回", ex: "She withdrew cash from the ATM." },
      { w: "account", p: "n.", zh: "账户", ex: "Open a business account online." },
      { w: "interest", p: "n.", zh: "利息；兴趣", ex: "The bank raised interest rates." },
      { w: "loan", p: "n.", zh: "贷款", ex: "They took out a loan to expand." },
      { w: "investment", p: "n.", zh: "投资", ex: "This is a safe investment." },
      { w: "stock", p: "n.", zh: "股票；库存", ex: "Tech stocks fell sharply yesterday." },
      { w: "refund", p: "n./v.", zh: "退款", ex: "I requested a full refund." },
      { w: "payment", p: "n.", zh: "付款；款项", ex: "Payment is due within 30 days." },
      { w: "receipt", p: "n.", zh: "收据", ex: "Keep the receipt for your records." },
      { w: "accounting", p: "n.", zh: "会计；财务", ex: "She works in accounting." },
      { w: "audit", p: "n./v.", zh: "审计", ex: "The accounts are audited yearly." },
      { w: "asset", p: "n.", zh: "资产", ex: "The building is a major asset." },
      { w: "liability", p: "n.", zh: "负债；责任", ex: "Long-term debts are liabilities." },
      { w: "transaction", p: "n.", zh: "交易", ex: "Check your recent transactions online." },
      { w: "exchange rate", p: "n.", zh: "汇率", ex: "The exchange rate changed today." },
      { w: "installment", p: "n.", zh: "分期付款", ex: "Pay in twelve monthly installments." },
      { w: "expenditure", p: "n.", zh: "支出；花费", ex: "Cut unnecessary expenditures." },
      { w: "statement", p: "n.", zh: "对账单；声明", ex: "Review your bank statement monthly." },
      { w: "funds", p: "n.", zh: "资金", ex: "Transfer the funds by Friday." }
    ]
  },
  {
    id: "retail", name: "购物客服", icon: "🛒",
    words: [
      { w: "discount", p: "n.", zh: "折扣", ex: "Members get a 10 percent discount." },
      { w: "purchase", p: "n./v.", zh: "购买", ex: "Keep proof of purchase." },
      { w: "exchange", p: "n./v.", zh: "换货；兑换", ex: "Can I exchange this shirt?" },
      { w: "out of stock", p: "phr.", zh: "缺货", ex: "The item is out of stock." },
      { w: "deliver", p: "v.", zh: "送货；递送", ex: "We deliver within two days." },
      { w: "warranty", p: "n.", zh: "保修（期）", ex: "The laptop has a two-year warranty." },
      { w: "customer service", p: "n.", zh: "客服", ex: "Contact customer service for help." },
      { w: "aisle", p: "n.", zh: "过道", ex: "Coffee is in aisle five." },
      { w: "checkout", p: "n.", zh: "收银台；结账", ex: "There are five people at the checkout." },
      { w: "price tag", p: "n.", zh: "价格标签", ex: "Check the price tag before paying." },
      { w: "on sale", p: "phr.", zh: "降价出售", ex: "Winter coats are on sale now." },
      { w: "merchandise", p: "n.", zh: "商品", ex: "The store displays new merchandise." },
      { w: "brand", p: "n.", zh: "品牌", ex: "This brand is very popular." },
      { w: "complaint", p: "n.", zh: "投诉", ex: "The manager handled the complaint well." },
      { w: "loyalty card", p: "n.", zh: "会员卡", ex: "Scan your loyalty card at checkout." },
      { w: "packaging", p: "n.", zh: "包装", ex: "The packaging was damaged." },
      { w: "retail price", p: "n.", zh: "零售价", ex: "The retail price is 120 dollars." },
      { w: "coupon", p: "n.", zh: "优惠券", ex: "Use this coupon at checkout." },
      { w: "inventory", p: "n.", zh: "库存；清单", ex: "The inventory is checked monthly." },
      { w: "restock", p: "v.", zh: "补货", ex: "We restock the shelves every morning." }
    ]
  },
  {
    id: "travel", name: "旅行交通", icon: "✈️",
    words: [
      { w: "flight", p: "n.", zh: "航班", ex: "The flight is on time." },
      { w: "boarding pass", p: "n.", zh: "登机牌", ex: "Show your boarding pass at the gate." },
      { w: "itinerary", p: "n.", zh: "行程表", ex: "Send me the trip itinerary." },
      { w: "accommodation", p: "n.", zh: "住宿", ex: "Book accommodation near the station." },
      { w: "reservation", p: "n.", zh: "预订", ex: "I have a reservation for two nights." },
      { w: "depart", p: "v.", zh: "出发；离开", ex: "The train departs at 9:15." },
      { w: "delay", p: "n./v.", zh: "延误", ex: "The flight was delayed two hours." },
      { w: "cancel", p: "v.", zh: "取消", ex: "The trip was canceled due to snow." },
      { w: "customs", p: "n.", zh: "海关", ex: "Go through customs before baggage claim." },
      { w: "luggage", p: "n.", zh: "行李", ex: "Collect your luggage at carousel three." },
      { w: "shuttle", p: "n.", zh: "班车；摆渡车", ex: "A free shuttle runs every 20 minutes." },
      { w: "commute", p: "v./n.", zh: "通勤", ex: "She commutes to work by train." },
      { w: "fare", p: "n.", zh: "车费；票价", ex: "The fare is 260 yen." },
      { w: "round trip", p: "n.", zh: "往返（票）", ex: "A round-trip ticket is cheaper." },
      { w: "terminal", p: "n.", zh: "航站楼；终点站", ex: "International flights leave from Terminal 2." },
      { w: "check in", p: "phr.", zh: "办理登机/入住", ex: "Check in online to save time." },
      { w: "destination", p: "n.", zh: "目的地", ex: "Kyoto is a popular destination." },
      { w: "landmark", p: "n.", zh: "地标", ex: "The tower is a famous landmark." },
      { w: "one-way ticket", p: "n.", zh: "单程票", ex: "I need a one-way ticket to Nagoya." },
      { w: "jet lag", p: "n.", zh: "时差反应", ex: "He recovered from jet lag in two days." }
    ]
  },
  {
    id: "dining", name: "餐饮酒店", icon: "🍽️",
    words: [
      { w: "reserve", p: "v.", zh: "预订", ex: "Reserve a table for six." },
      { w: "menu", p: "n.", zh: "菜单", ex: "The menu changes seasonally." },
      { w: "appetizer", p: "n.", zh: "开胃菜", ex: "We ordered two appetizers." },
      { w: "beverage", p: "n.", zh: "饮品", ex: "Beverages are included in the price." },
      { w: "banquet", p: "n.", zh: "宴会", ex: "The banquet hall seats 200 guests." },
      { w: "catering", p: "n.", zh: "餐饮承办", ex: "We hired a catering company." },
      { w: "tip", p: "n.", zh: "小费", ex: "Leave a tip for the waiter." },
      { w: "lobby", p: "n.", zh: "大堂", ex: "Wait for me in the hotel lobby." },
      { w: "suite", p: "n.", zh: "套房", ex: "They booked the honeymoon suite." },
      { w: "amenity", p: "n.", zh: "设施；便利服务", ex: "The gym is a popular amenity." },
      { w: "housekeeping", p: "n.", zh: "客房服务；保洁", ex: "Housekeeping cleans the rooms daily." },
      { w: "concierge", p: "n.", zh: "礼宾员；前台服务", ex: "Ask the concierge for restaurant advice." },
      { w: "cuisine", p: "n.", zh: "菜肴；烹饪", ex: "Italian cuisine is popular here." },
      { w: "special", p: "n.", zh: "特色菜；特价", ex: "Today's special is grilled fish." },
      { w: "vegetarian", p: "n./a.", zh: "素食者；素的", ex: "Is there a vegetarian option?" },
      { w: "vacancy", p: "n.", zh: "空房；空缺", ex: "Sorry, we have no vacancy tonight." },
      { w: "bill", p: "n.", zh: "账单", ex: "Could we have the bill, please?" },
      { w: "buffet", p: "n.", zh: "自助餐", ex: "Breakfast is served as a buffet." },
      { w: "check-out time", p: "n.", zh: "退房时间", ex: "Check-out time is 11 a.m." },
      { w: "complimentary", p: "a.", zh: "免费赠送的", ex: "Complimentary water in every room." }
    ]
  },
  {
    id: "tech", name: "技术设备", icon: "💻",
    words: [
      { w: "install", p: "v.", zh: "安装", ex: "Install the latest update tonight." },
      { w: "upgrade", p: "v./n.", zh: "升级", ex: "The system will be upgraded on Sunday." },
      { w: "malfunction", p: "n./v.", zh: "故障", ex: "The scanner malfunctioned again." },
      { w: "repair", p: "n./v.", zh: "修理", ex: "The repair will take two days." },
      { w: "maintenance", p: "n.", zh: "维护；保养", ex: "Scheduled maintenance is on Sunday." },
      { w: "equipment", p: "n.", zh: "设备", ex: "Handle the equipment carefully." },
      { w: "device", p: "n.", zh: "设备；装置", ex: "Connect your device to the Wi-Fi." },
      { w: "network", p: "n.", zh: "网络", ex: "The network is slow today." },
      { w: "server", p: "n.", zh: "服务器", ex: "The server is down this morning." },
      { w: "software", p: "n.", zh: "软件", ex: "This software is free for staff." },
      { w: "download", p: "v.", zh: "下载", ex: "Download the report from the site." },
      { w: "attach", p: "v.", zh: "附上；附加", ex: "Attach the file to the e-mail." },
      { w: "back up", p: "phr.", zh: "备份", ex: "Back up your files daily." },
      { w: "compatible", p: "a.", zh: "兼容的", ex: "It is compatible with all systems." },
      { w: "troubleshoot", p: "v.", zh: "排查故障", ex: "Restart the device to troubleshoot." },
      { w: "manual", p: "n.", zh: "说明书；手册", ex: "Read the manual before use." },
      { w: "settings", p: "n.", zh: "设置", ex: "Change the settings to dark mode." },
      { w: "battery", p: "n.", zh: "电池", ex: "The battery needs replacing." },
      { w: "password", p: "n.", zh: "密码", ex: "Reset your password by e-mail." },
      { w: "delete", p: "v.", zh: "删除", ex: "Delete the old version of the file." }
    ]
  },
  {
    id: "property", name: "建筑房产", icon: "🏗️",
    words: [
      { w: "construct", p: "v.", zh: "建造", ex: "A new bridge is being constructed." },
      { w: "renovate", p: "v.", zh: "翻新；整修", ex: "They renovated the hotel lobby." },
      { w: "contractor", p: "n.", zh: "承包商", ex: "Hire a licensed contractor." },
      { w: "blueprint", p: "n.", zh: "蓝图；设计图", ex: "The blueprint needs approval." },
      { w: "permit", p: "n.", zh: "许可证", ex: "Apply for a building permit first." },
      { w: "inspection", p: "n.", zh: "检查；验收", ex: "The safety inspection passed." },
      { w: "lease", p: "n.", zh: "租约", ex: "The lease ends in March." },
      { w: "tenant", p: "n.", zh: "租户", ex: "Tenants must report water leaks." },
      { w: "landlord", p: "n.", zh: "房东", ex: "The landlord fixed the heater." },
      { w: "rent", p: "n./v.", zh: "租金；租用", ex: "Rent is due on the first." },
      { w: "property", p: "n.", zh: "房产；地产", ex: "The property sells for 500,000 dollars." },
      { w: "facility", p: "n.", zh: "设施", ex: "The facility has a large cafeteria." },
      { w: "expand", p: "v.", zh: "扩建；扩张", ex: "The factory will expand next year." },
      { w: "architect", p: "n.", zh: "建筑师", ex: "The architect designed the tower." },
      { w: "estimate", p: "n./v.", zh: "估价；估计", ex: "Get an estimate before the repairs." },
      { w: "completion", p: "n.", zh: "完工", ex: "Completion is set for June." },
      { w: "site", p: "n.", zh: "工地；场所", ex: "Hard hats are required on site." },
      { w: "demolish", p: "v.", zh: "拆除", ex: "The old wing was demolished." },
      { w: "occupancy", p: "n.", zh: "入住；占用", ex: "The office reached full occupancy." },
      { w: "utilities", p: "n.", zh: "水电煤气费", ex: "Utilities are included in the rent." }
    ]
  },
  {
    id: "marketing", name: "广告营销", icon: "📣",
    words: [
      { w: "campaign", p: "n.", zh: "宣传活动；广告战", ex: "The ad campaign starts on Monday." },
      { w: "advertise", p: "v.", zh: "做广告", ex: "They advertise on social media." },
      { w: "commercial", p: "n.", zh: "电视广告", ex: "The commercial aired during the game." },
      { w: "billboard", p: "n.", zh: "广告牌", ex: "A new billboard went up downtown." },
      { w: "slogan", p: "n.", zh: "口号；广告语", ex: "The new slogan is easy to remember." },
      { w: "target audience", p: "n.", zh: "目标受众", ex: "Know your target audience well." },
      { w: "launch", p: "v.", zh: "发布；推出", ex: "Launch the product in May." },
      { w: "survey", p: "n.", zh: "调查", ex: "Fill out the customer survey." },
      { w: "feedback", p: "n.", zh: "反馈", ex: "We value your feedback." },
      { w: "market share", p: "n.", zh: "市场份额", ex: "Market share grew to 20 percent." },
      { w: "brand image", p: "n.", zh: "品牌形象", ex: "The ad improved the brand image." },
      { w: "endorsement", p: "n.", zh: "名人代言", ex: "The athlete signed an endorsement deal." },
      { w: "newsletter", p: "n.", zh: "（内部）时事通讯", ex: "Subscribe to our monthly newsletter." },
      { w: "brochure", p: "n.", zh: "小册子", ex: "Pick up a brochure at the desk." },
      { w: "flyer", p: "n.", zh: "传单", ex: "Hand out flyers at the station." },
      { w: "subscribe", p: "v.", zh: "订阅", ex: "Subscribe before Friday for a discount." },
      { w: "promotion", p: "n.", zh: "促销；晋升", ex: "The spring promotion begins today." },
      { w: "publicity", p: "n.", zh: "宣传；曝光", ex: "The event got free publicity." },
      { w: "distribute", p: "v.", zh: "分发；分配", ex: "Distribute the samples to shoppers." },
      { w: "consumer", p: "n.", zh: "消费者", ex: "Consumers prefer eco-friendly goods." }
    ]
  },
  {
    id: "phrases", name: "高频短语", icon: "💬",
    words: [
      { w: "take over", p: "phr.", zh: "接管；接任", ex: "A new CEO will take over in June." },
      { w: "look into", p: "phr.", zh: "调查；研究", ex: "We are looking into the cause of the delay." },
      { w: "run out of", p: "phr.", zh: "用完；耗尽", ex: "We ran out of printer paper." },
      { w: "put off", p: "phr.", zh: "推迟", ex: "The meeting was put off until Monday." },
      { w: "carry out", p: "phr.", zh: "执行；实施", ex: "Carry out the plan as scheduled." },
      { w: "break down", p: "phr.", zh: "出故障；坏掉", ex: "The elevator broke down again." },
      { w: "get back to", p: "phr.", zh: "稍后回复", ex: "I will get back to you by noon." },
      { w: "hold off", p: "phr.", zh: "推迟；暂停", ex: "Let's hold off until prices drop." },
      { w: "in charge of", p: "phr.", zh: "负责；主管", ex: "She is in charge of the sales team." },
      { w: "on behalf of", p: "phr.", zh: "代表", ex: "He spoke on behalf of the team." },
      { w: "up to date", p: "phr.", zh: "最新的；现时的", ex: "Keep the records up to date." },
      { w: "as soon as possible", p: "phr.", zh: "尽快", ex: "Please reply as soon as possible." },
      { w: "be scheduled to", p: "phr.", zh: "定于；按计划", ex: "The plane is scheduled to leave at noon." },
      { w: "look forward to", p: "phr.", zh: "期待", ex: "I look forward to hearing from you." },
      { w: "comply with", p: "phr.", zh: "遵守", ex: "Comply with all safety regulations." },
      { w: "prior to", p: "phr.", zh: "在……之前", ex: "Confirm the details prior to departure." },
      { w: "in advance", p: "phr.", zh: "提前；预先", ex: "Book two weeks in advance." },
      { w: "no later than", p: "phr.", zh: "不晚于", ex: "Arrive no later than 8:30." },
      { w: "be familiar with", p: "phr.", zh: "熟悉", ex: "Are you familiar with this software?" },
      { w: "fill out", p: "phr.", zh: "填写（表格）", ex: "Fill out this form first, please." },
      { w: "turn in", p: "phr.", zh: "提交；上交", ex: "Turn in your report by Friday." },
      { w: "come up with", p: "phr.", zh: "想出；提出", ex: "She came up with a great idea." },
      { w: "keep up with", p: "phr.", zh: "跟上；保持同步", ex: "It is hard to keep up with the changes." },
      { w: "deal with", p: "phr.", zh: "处理；应对", ex: "She deals with customer complaints." },
      { w: "participate in", p: "phr.", zh: "参加", ex: "All staff can participate in the training." },
      { w: "be involved in", p: "phr.", zh: "参与；涉及", ex: "He is involved in the new project." },
      { w: "depend on", p: "phr.", zh: "取决于；依靠", ex: "Delivery time depends on the weather." },
      { w: "apply for", p: "phr.", zh: "申请", ex: "Apply for the position online." },
      { w: "turn down", p: "phr.", zh: "拒绝；调低", ex: "They turned down our offer." },
      { w: "set up", p: "phr.", zh: "设置；建立", ex: "Set up the projector before nine." },
      { w: "show up", p: "phr.", zh: "出席；出现", ex: "Only ten people showed up." },
      { w: "go over", p: "phr.", zh: "检查；讨论", ex: "Let's go over the figures again." },
      { w: "work on", p: "phr.", zh: "致力于；处理", ex: "We are working on the budget now." },
      { w: "be available for", p: "phr.", zh: "可用于；有空", ex: "Is the room available for tomorrow?" },
      { w: "at your earliest convenience", p: "phr.", zh: "尽早（商务信函）", ex: "Please reply at your earliest convenience." },
      { w: "for the time being", p: "phr.", zh: "暂时", ex: "For the time being, work from home." },
      { w: "in the meantime", p: "phr.", zh: "与此同时", ex: "In the meantime, use the old system." },
      { w: "on schedule", p: "phr.", zh: "按计划进行", ex: "The project is on schedule." },
      { w: "behind schedule", p: "phr.", zh: "进度落后", ex: "The launch is behind schedule." },
      { w: "meet the deadline", p: "phr.", zh: "赶上截止日期", ex: "We met the deadline by two days." },
      { w: "be subject to", p: "phr.", zh: "视……而定；可能受……影响", ex: "Prices are subject to change." },
      { w: "take steps", p: "phr.", zh: "采取措施", ex: "The firm took steps to improve safety." }
    ]
  },
  {
    id: "medical", name: "医疗健康", icon: "🏥",
    words: [
      { w: "checkup", p: "n.", zh: "体检", ex: "Employees can get a free annual health checkup." },
      { w: "physician", p: "n.", zh: "内科医生", ex: "Consult your physician before starting the diet." },
      { w: "prescription", p: "n.", zh: "处方", ex: "You need a prescription for this medicine." },
      { w: "pharmacy", p: "n.", zh: "药店", ex: "Pick up the medicine at the pharmacy downstairs." },
      { w: "symptom", p: "n.", zh: "症状", ex: "Common symptoms include fever and fatigue." },
      { w: "treatment", p: "n.", zh: "治疗；待遇", ex: "The treatment lasts about two weeks." },
      { w: "injury", p: "n.", zh: "受伤", ex: "He reported the injury to his supervisor." },
      { w: "first aid", p: "phr.", zh: "急救", ex: "The first aid kit is in the break room." },
      { w: "emergency", p: "n.", zh: "紧急情况", ex: "In an emergency, call the front desk." },
      { w: "dosage", p: "n.", zh: "剂量", ex: "Follow the dosage instructions on the label." },
      { w: "side effect", p: "phr.", zh: "副作用", ex: "The medicine may cause side effects." },
      { w: "allergy", p: "n.", zh: "过敏", ex: "Please list any food allergies on the form." },
      { w: "vaccination", p: "n.", zh: "疫苗接种", ex: "Flu vaccinations are offered every autumn." },
      { w: "therapist", p: "n.", zh: "治疗师", ex: "The therapist taught him stretching exercises." },
      { w: "medical leave", p: "phr.", zh: "病假", ex: "She took a week of medical leave." },
      { w: "health insurance", p: "phr.", zh: "医疗保险", ex: "Health insurance covers most of the cost." },
      { w: "insurance claim", p: "phr.", zh: "保险理赔", ex: "File the insurance claim within thirty days." },
      { w: "dental", p: "a.", zh: "牙科的", ex: "Book a dental appointment for Friday." },
      { w: "clinic", p: "n.", zh: "诊所", ex: "The clinic opens at eight a.m." },
      { w: "recover", p: "v.", zh: "康复；恢复", ex: "He is recovering well after the surgery." }
    ]
  },
  {
    id: "logistics", name: "物流运输", icon: "🚚",
    words: [
      { w: "shipment", p: "n.", zh: "装运的货物", ex: "The shipment left the factory on Monday." },
      { w: "freight", p: "n.", zh: "货运", ex: "Sea freight is cheaper than air freight." },
      { w: "warehouse", p: "n.", zh: "仓库", ex: "The warehouse is near the port." },
      { w: "cargo", p: "n.", zh: "货物", ex: "The cargo was inspected at customs." },
      { w: "container", p: "n.", zh: "集装箱", ex: "Load the containers onto the ship." },
      { w: "loading dock", p: "phr.", zh: "装卸月台", ex: "Trucks unload at loading dock five." },
      { w: "pallet", p: "n.", zh: "托盘", ex: "Move the pallets with a forklift." },
      { w: "supply chain", p: "phr.", zh: "供应链", ex: "The flood disrupted the supply chain." },
      { w: "distributor", p: "n.", zh: "分销商", ex: "Our distributor covers the Kansai region." },
      { w: "courier", p: "n.", zh: "快递员；快递公司", ex: "The courier will pick it up at three." },
      { w: "tracking number", p: "phr.", zh: "物流追踪号", ex: "Enter the tracking number on the website." },
      { w: "dispatch", p: "v.", zh: "发出；派遣", ex: "Orders are dispatched within 24 hours." },
      { w: "recipient", p: "n.", zh: "收件人", ex: "Write the recipient's address clearly." },
      { w: "in stock", p: "phr.", zh: "有货", ex: "The item is back in stock." },
      { w: "backorder", p: "n.", zh: "延期交货订单", ex: "The part is on backorder until May." },
      { w: "lead time", p: "phr.", zh: "交付周期", ex: "The lead time is two weeks." },
      { w: "customs clearance", p: "phr.", zh: "清关", ex: "Customs clearance took three days." },
      { w: "bulky", p: "a.", zh: "大件的", ex: "Bulky items ship by ground." },
      { w: "fragile", p: "a.", zh: "易碎的", ex: "Mark the box fragile." },
      { w: "consignment", p: "n.", zh: "托运的一批货物", ex: "A consignment of spare parts arrived." }
    ]
  },
  {
    id: "legal", name: "法律合同", icon: "⚖️",
    words: [
      { w: "agreement", p: "n.", zh: "协议", ex: "Both sides signed the agreement." },
      { w: "terms and conditions", p: "phr.", zh: "条款与条件", ex: "Read the terms and conditions carefully." },
      { w: "clause", p: "n.", zh: "（合同）条款", ex: "Clause five covers payment terms." },
      { w: "breach", p: "n./v.", zh: "违反（合同）", ex: "Late delivery is a breach of contract." },
      { w: "terminate", p: "v.", zh: "终止", ex: "Either party may terminate with notice." },
      { w: "renewal", p: "n.", zh: "续约；续期", ex: "The lease is up for renewal in June." },
      { w: "penalty", p: "n.", zh: "违约金；处罚", ex: "A penalty applies to late payments." },
      { w: "comply with", p: "phr.", zh: "遵守（法规）", ex: "All firms must comply with the new rules." },
      { w: "regulation", p: "n.", zh: "法规", ex: "Safety regulations were updated." },
      { w: "license", p: "n.", zh: "许可证", ex: "Renew your business license annually." },
      { w: "patent", p: "n.", zh: "专利", ex: "The company holds ten patents." },
      { w: "trademark", p: "n.", zh: "商标", ex: "Register the trademark in each market." },
      { w: "copyright", p: "n.", zh: "版权", ex: "The material is protected by copyright." },
      { w: "lawsuit", p: "n.", zh: "诉讼", ex: "The lawsuit was settled out of court." },
      { w: "attorney", p: "n.", zh: "律师", ex: "Consult an attorney before signing." },
      { w: "dispute", p: "n.", zh: "争议", ex: "The wage dispute ended in mediation." },
      { w: "arbitration", p: "n.", zh: "仲裁", ex: "Disputes go to arbitration first." },
      { w: "confidentiality", p: "n.", zh: "保密", ex: "Employees sign a confidentiality agreement." },
      { w: "liability", p: "n.", zh: "法律责任；负债", ex: "The firm has limited liability." },
      { w: "legislation", p: "n.", zh: "法律；立法", ex: "New legislation takes effect in April." }
    ]
  },
  {
    id: "environment", name: "环境能源", icon: "🌱",
    words: [
      { w: "recycle", p: "v.", zh: "回收利用", ex: "Recycle paper and plastic separately." },
      { w: "recycling bin", p: "phr.", zh: "回收箱", ex: "Use the blue recycling bin." },
      { w: "emission", p: "n.", zh: "排放物", ex: "The plant cut carbon emissions by half." },
      { w: "sustainable", p: "a.", zh: "可持续的", ex: "We favor sustainable packaging." },
      { w: "renewable", p: "a.", zh: "可再生的", ex: "Wind is a renewable energy source." },
      { w: "solar panel", p: "phr.", zh: "太阳能板", ex: "Solar panels were installed on the roof." },
      { w: "energy-efficient", p: "a.", zh: "节能的", ex: "Buy energy-efficient appliances." },
      { w: "carbon footprint", p: "phr.", zh: "碳足迹", ex: "The audit measured the plant's carbon footprint." },
      { w: "conservation", p: "n.", zh: "保护；节约", ex: "Water conservation is a company priority." },
      { w: "pollution", p: "n.", zh: "污染", ex: "Air pollution levels fell this year." },
      { w: "dispose of", p: "phr.", zh: "丢弃；处理掉", ex: "Dispose of batteries properly." },
      { w: "eco-friendly", p: "a.", zh: "环保的", ex: "Consumers prefer eco-friendly products." },
      { w: "biodegradable", p: "a.", zh: "可生物降解的", ex: "The cups are biodegradable." },
      { w: "greenhouse gas", p: "phr.", zh: "温室气体", ex: "Greenhouse gases must be reported." },
      { w: "waste reduction", p: "phr.", zh: "减废", ex: "The plant set a waste reduction goal." },
      { w: "environmental impact", p: "phr.", zh: "环境影响", ex: "Study the project's environmental impact." },
      { w: "preserve", p: "v.", zh: "保护；保存", ex: "We preserve the forest around the site." },
      { w: "alternative energy", p: "phr.", zh: "替代能源", ex: "The firm invests in alternative energy." },
      { w: "power plant", p: "phr.", zh: "发电厂", ex: "The power plant switched to gas." },
      { w: "leak", p: "n./v.", zh: "泄漏", ex: "Report any chemical leak at once." }
    ]
  },
  {
    id: "entertainment", name: "娱乐休闲", icon: "🎭",
    words: [
      { w: "admission", p: "n.", zh: "入场费；进入", ex: "Admission is free for members." },
      { w: "exhibit", p: "n.", zh: "展览", ex: "The photography exhibit runs until May." },
      { w: "gallery", p: "n.", zh: "美术馆；画廊", ex: "The gallery opens at ten." },
      { w: "performance", p: "n.", zh: "演出", ex: "The performance starts at seven." },
      { w: "auditorium", p: "n.", zh: "礼堂", ex: "The talk is in the main auditorium." },
      { w: "rehearsal", p: "n.", zh: "排练", ex: "The rehearsal is at six p.m." },
      { w: "box office", p: "phr.", zh: "售票处", ex: "Tickets are sold at the box office." },
      { w: "venue", p: "n.", zh: "场馆", ex: "The venue holds two hundred people." },
      { w: "season ticket", p: "phr.", zh: "季票", ex: "Season tickets go on sale Monday." },
      { w: "preview", p: "n.", zh: "预演；预告", ex: "Attend the preview next week." },
      { w: "guided tour", p: "phr.", zh: "导览游览", ex: "Join the guided tour at two." },
      { w: "recreational", p: "a.", zh: "娱乐消遣的", ex: "The center offers recreational programs." },
      { w: "fitness center", p: "phr.", zh: "健身中心", ex: "The fitness center opens at five a.m." },
      { w: "membership", p: "n.", zh: "会员资格", ex: "Membership includes pool access." },
      { w: "annual pass", p: "phr.", zh: "年票", ex: "Buy an annual pass and save." },
      { w: "art collection", p: "phr.", zh: "艺术收藏", ex: "The museum's art collection expanded." },
      { w: "festival", p: "n.", zh: "节；节庆活动", ex: "The film festival begins in June." },
      { w: "amateur", p: "a./n.", zh: "业余的（人）", ex: "An amateur choir performed." },
      { w: "exhibition hall", p: "phr.", zh: "展厅", ex: "The auto show fills two exhibition halls." },
      { w: "refreshment", p: "n.", zh: "茶点；饮料", ex: "Refreshments will be served afterward." }
    ]
  },
  {
    id: "email", name: "邮件沟通", icon: "📧",
    words: [
      { w: "attach", p: "v.", zh: "附上（附件）", ex: "Please attach the invoice." },
      { w: "attachment", p: "n.", zh: "附件", ex: "The attachment is too large." },
      { w: "forward", p: "v.", zh: "转发", ex: "Forward the message to HR." },
      { w: "reply", p: "n./v.", zh: "回复", ex: "Thanks for your prompt reply." },
      { w: "cc", p: "v.", zh: "抄送", ex: "Cc your manager on the request." },
      { w: "subject line", p: "phr.", zh: "邮件主题栏", ex: "Keep the subject line clear." },
      { w: "follow up", p: "phr.", zh: "跟进", ex: "I'll follow up early next week." },
      { w: "confirm receipt", p: "phr.", zh: "确认收到", ex: "Please confirm receipt of this e-mail." },
      { w: "typo", p: "n.", zh: "打字错误", ex: "There is a typo in the date." },
      { w: "draft", p: "n./v.", zh: "草稿", ex: "Save the draft and finish later." },
      { w: "proofread", p: "v.", zh: "校对", ex: "Proofread the report before sending." },
      { w: "inbox", p: "n.", zh: "收件箱", ex: "Your inbox is full." },
      { w: "out of office", p: "phr.", zh: "不在办公室（自动回复）", ex: "Set an out-of-office reply." },
      { w: "clarify", p: "v.", zh: "澄清；说明", ex: "Let me clarify the schedule." },
      { w: "notify", p: "v.", zh: "通知", ex: "We will notify winners by e-mail." },
      { w: "apologize", p: "v.", zh: "道歉", ex: "We apologize for the delay." },
      { w: "inquire", p: "v.", zh: "询问", ex: "A client inquired about discounts." },
      { w: "remind", p: "v.", zh: "提醒", ex: "Remind the team about the deadline." },
      { w: "update", p: "n./v.", zh: "更新；最新消息", ex: "Here is a quick update on progress." },
      { w: "miscommunication", p: "n.", zh: "沟通失误", ex: "The delay was due to a miscommunication." }
    ]
  },
  {
    id: "data", name: "图表数据", icon: "📊",
    words: [
      { w: "graph", p: "n.", zh: "曲线图", ex: "The graph shows sales by region." },
      { w: "chart", p: "n.", zh: "图表", ex: "See the pie chart on page three." },
      { w: "figure", p: "n.", zh: "数字；图表", ex: "The figures improved in the second quarter." },
      { w: "statistics", p: "n.", zh: "统计数据", ex: "The statistics cover five years." },
      { w: "percentage", p: "n.", zh: "百分比", ex: "Costs rose by one percentage point." },
      { w: "peak", p: "n./v.", zh: "峰值；达到峰值", ex: "Demand peaks in December." },
      { w: "decline", p: "n./v.", zh: "下降", ex: "Exports declined last year." },
      { w: "average", p: "n./a.", zh: "平均（的）", ex: "The average price held steady." },
      { w: "projection", p: "n.", zh: "预测；预估", ex: "The projection assumes 3 percent growth." },
      { w: "survey results", p: "phr.", zh: "调查结果", ex: "Survey results are on the intranet." },
      { w: "trend", p: "n.", zh: "趋势", ex: "The upward trend continued." },
      { w: "ratio", p: "n.", zh: "比率", ex: "The ratio of staff to managers is 10 to 1." },
      { w: "substantially", p: "adv.", zh: "大幅地", ex: "Output grew substantially." },
      { w: "steadily", p: "adv.", zh: "稳步地", ex: "Profits rose steadily." },
      { w: "gradually", p: "adv.", zh: "逐渐地", ex: "Costs fell gradually." },
      { w: "significantly", p: "adv.", zh: "显著地", ex: "Sales dropped significantly." },
      { w: "fluctuate", p: "v.", zh: "波动", ex: "Prices fluctuated all month." },
      { w: "roughly", p: "adv.", zh: "大约", ex: "Roughly half of the staff responded." },
      { w: "majority", p: "n.", zh: "大多数", ex: "A majority chose option B." },
      { w: "double", p: "v.", zh: "翻倍", ex: "Revenue doubled in two years." }
    ]
  },
  {
    id: "bank", name: "银行保险", icon: "🏦",
    words: [
      { w: "teller", p: "n.", zh: "银行柜员", ex: "Queue for the next available teller." },
      { w: "deposit slip", p: "phr.", zh: "存款单", ex: "Fill out a deposit slip first." },
      { w: "withdrawal", p: "n.", zh: "取款", ex: "Withdrawals over the counter need ID." },
      { w: "transfer", p: "n./v.", zh: "转账", ex: "Make the transfer by Friday." },
      { w: "balance", p: "n.", zh: "余额", ex: "Check your account balance online." },
      { w: "mortgage", p: "n.", zh: "按揭贷款", ex: "They took a 25-year mortgage." },
      { w: "premium", p: "n.", zh: "保险费", ex: "The annual premium is 60,000 yen." },
      { w: "coverage", p: "n.", zh: "保险范围；覆盖", ex: "The plan has full dental coverage." },
      { w: "policy", p: "n.", zh: "保险单；政策", ex: "Review your insurance policy yearly." },
      { w: "claim", p: "n./v.", zh: "索赔", ex: "Submit the claim with receipts." },
      { w: "beneficiary", p: "n.", zh: "受益人", ex: "Name a beneficiary on the form." },
      { w: "credit rating", p: "phr.", zh: "信用评级", ex: "A good credit rating lowers costs." },
      { w: "collateral", p: "n.", zh: "抵押品", ex: "The loan needs collateral." },
      { w: "overdraft", p: "n.", zh: "透支", ex: "Overdraft fees apply after the grace period." },
      { w: "currency", p: "n.", zh: "货币", ex: "Exchange foreign currency at the counter." },
      { w: "savings account", p: "phr.", zh: "储蓄账户", ex: "Open a savings account online." },
      { w: "interest rate", p: "phr.", zh: "利率", ex: "Interest rates may rise next year." },
      { w: "appraisal", p: "n.", zh: "估价；评估", ex: "An appraisal set the value at 40 million yen." },
      { w: "installment plan", p: "phr.", zh: "分期付款计划", ex: "Buy it on an installment plan." },
      { w: "insure", p: "v.", zh: "投保", ex: "Insure the shipment against damage." }
    ]
  },
  {
    id: "adjectives", name: "形容词宝库", icon: "🎨",
    words: [
      { w: "efficient", p: "a.", zh: "高效的", ex: "The new system is more efficient." },
      { w: "adequate", p: "a.", zh: "足够的；充分的", ex: "Make sure the lighting is adequate." },
      { w: "extensive", p: "a.", zh: "广泛的；大量的", ex: "She has extensive experience in sales." },
      { w: "thorough", p: "a.", zh: "彻底的；全面的", ex: "Thank you for the thorough review." },
      { w: "prompt", p: "a.", zh: "及时的；迅速的", ex: "We appreciate your prompt reply." },
      { w: "feasible", p: "a.", zh: "可行的", ex: "Is the proposed schedule feasible?" },
      { w: "courteous", p: "a.", zh: "有礼貌的", ex: "Staff should be courteous at all times." },
      { w: "durable", p: "a.", zh: "耐用的", ex: "These chairs are durable and easy to clean." },
      { w: "spacious", p: "a.", zh: "宽敞的", ex: "The new office is more spacious." },
      { w: "convenient", p: "a.", zh: "方便的", ex: "Is Monday convenient for you?" },
      { w: "reliable", p: "a.", zh: "可靠的", ex: "A reliable supplier is hard to find." },
      { w: "flexible", p: "a.", zh: "灵活的；有弹性的", ex: "We offer flexible working hours." },
      { w: "mandatory", p: "a.", zh: "强制性的", ex: "Attendance at the briefing is mandatory." },
      { w: "optional", p: "a.", zh: "可选的", ex: "The afternoon workshop is optional." },
      { w: "temporary", p: "a.", zh: "暂时的", ex: "She was hired on a temporary basis." },
      { w: "permanent", p: "a.", zh: "永久的", ex: "He was offered a permanent position." },
      { w: "substantial", p: "a.", zh: "大量的；可观的", ex: "A substantial discount is offered this week." },
      { w: "gradual", p: "a.", zh: "逐渐的", ex: "There will be a gradual transition to the new system." },
      { w: "excessive", p: "a.", zh: "过度的；过多的", ex: "Avoid excessive spending on travel." },
      { w: "numerous", p: "a.", zh: "众多的", ex: "Numerous customers praised the service." }
    ]
  },
  {
    id: "safety", name: "安全守则", icon: "⚠️",
    words: [
      { w: "hazard", p: "n.", zh: "危险；隐患", ex: "Report any hazard to your supervisor." },
      { w: "evacuation", p: "n.", zh: "疏散；撤离", ex: "Follow the evacuation route signs." },
      { w: "fire drill", p: "phr.", zh: "消防演习", ex: "A fire drill is scheduled for Friday." },
      { w: "fire extinguisher", p: "n.", zh: "灭火器", ex: "Know where the nearest fire extinguisher is." },
      { w: "emergency exit", p: "n.", zh: "安全出口", ex: "Keep emergency exits clear at all times." },
      { w: "safety helmet", p: "n.", zh: "安全帽", ex: "Visitors must wear a safety helmet on site." },
      { w: "precaution", p: "n.", zh: "预防措施", ex: "Take precautions when lifting heavy boxes." },
      { w: "hazardous", p: "a.", zh: "危险的", ex: "Store hazardous materials in locked cabinets." },
      { w: "flammable", p: "a.", zh: "易燃的", ex: "Keep flammable liquids away from heat." },
      { w: "restricted area", p: "phr.", zh: "限制进入区域", ex: "This is a restricted area; badge required." },
      { w: "authorized", p: "a.", zh: "经授权的", ex: "Only authorized staff may enter the lab." },
      { w: "accident", p: "n.", zh: "事故", ex: "Report every accident, however minor." },
      { w: "slippery", p: "a.", zh: "湿滑的", ex: "Caution: the floor is slippery when wet." },
      { w: "caution", p: "n.", zh: "小心；警告", ex: "Handle the glass with caution." },
      { w: "evacuate", p: "v.", zh: "撤离", ex: "Evacuate the building when the alarm sounds." },
      { w: "prevent", p: "v.", zh: "预防；防止", ex: "Regular checks prevent most breakdowns." },
      { w: "protective gear", p: "phr.", zh: "防护装备", ex: "Wear protective gear in the workshop." },
      { w: "risk", p: "n.", zh: "风险", ex: "Assess the risks before starting the job." },
      { w: "warning sign", p: "phr.", zh: "警示标志", ex: "Obey all warning signs in the plant." },
      { w: "secure", p: "v.", zh: "固定；使安全", ex: "Secure the ladder before climbing it." }
    ]
  },
  {
    id: "manufacturing", name: "制造生产", icon: "🏭",
    words: [
      { w: "assembly line", p: "phr.", zh: "装配线", ex: "The assembly line runs around the clock." },
      { w: "output", p: "n.", zh: "产量；产出", ex: "Monthly output rose by 12 percent." },
      { w: "defect", p: "n.", zh: "缺陷；瑕疵", ex: "Every defect must be logged and analyzed." },
      { w: "quality control", p: "phr.", zh: "质量管理", ex: "Quality control inspects every batch." },
      { w: "batch", p: "n.", zh: "一批（产品）", ex: "A batch of 500 units shipped today." },
      { w: "machinery", p: "n.", zh: "机器（总称）", ex: "Old machinery will be replaced next year." },
      { w: "automated", p: "a.", zh: "自动化的", ex: "The warehouse is fully automated." },
      { w: "capacity", p: "n.", zh: "产能；容量", ex: "The plant is running at full capacity." },
      { w: "raw material", p: "phr.", zh: "原材料", ex: "Raw material prices keep rising." },
      { w: "manufacture", p: "v.", zh: "制造；生产", ex: "The parts are manufactured locally." },
      { w: "component", p: "n.", zh: "零件；部件", ex: "Each component has a serial number." },
      { w: "recall", p: "n./v.", zh: "召回", ex: "The company recalled 10,000 cars." },
      { w: "defective", p: "a.", zh: "有缺陷的", ex: "Return defective items to the supplier." },
      { w: "productivity", p: "n.", zh: "生产率", ex: "Productivity improved after the upgrade." },
      { w: "plant", p: "n.", zh: "工厂", ex: "The Nagoya plant employs 800 workers." },
      { w: "industrial", p: "a.", zh: "工业的", ex: "The area is zoned for industrial use." },
      { w: "conveyor belt", p: "phr.", zh: "传送带", ex: "Products move along the conveyor belt." },
      { w: "fabricate", p: "v.", zh: "制造；组装", ex: "The frames are fabricated in-house." },
      { w: "prototype", p: "n.", zh: "原型；样品", ex: "The prototype passed all safety tests." },
      { w: "downtime", p: "n.", zh: "停机时间；故障期", ex: "Downtime costs the factory thousands daily." }
    ]
  },
  {
    id: "meetings", name: "会议日程", icon: "📅",
    words: [
      { w: "convene", p: "v.", zh: "召集；开会", ex: "The committee will convene at nine." },
      { w: "reschedule", p: "v.", zh: "改期；重新安排", ex: "Can we reschedule to Thursday?" },
      { w: "attend", p: "v.", zh: "出席；参加", ex: "All managers are expected to attend." },
      { w: "absent", p: "a.", zh: "缺席的", ex: "Three members were absent today." },
      { w: "adjourn", p: "v.", zh: "休会；散会", ex: "The meeting adjourned at noon." },
      { w: "postpone", p: "v.", zh: "推迟", ex: "They postponed the vote until May." },
      { w: "tentative", p: "a.", zh: "暂定的", ex: "The date is tentative and may change." },
      { w: "confirm", p: "v.", zh: "确认", ex: "Please confirm your attendance by e-mail." },
      { w: "circulate", p: "v.", zh: "传阅；分发", ex: "Circulate the agenda before the meeting." },
      { w: "materials", p: "n.", zh: "材料；资料", ex: "Meeting materials are in the shared folder." },
      { w: "call off", p: "phr.", zh: "取消", ex: "The retreat was called off." },
      { w: "brief", p: "v./a.", zh: "简报；简短的", ex: "The director will brief us at ten." },
      { w: "recap", p: "n./v.", zh: "回顾；概要", ex: "Let me recap the main points." },
      { w: "preliminary", p: "a.", zh: "初步的；预备的", ex: "Preliminary results look promising." },
      { w: "annual", p: "a.", zh: "每年的", ex: "The annual review is in March." },
      { w: "quarterly", p: "a.", zh: "每季度的", ex: "Quarterly reports are due Friday." },
      { w: "upcoming", p: "a.", zh: "即将到来的", ex: "Prepare for the upcoming audit." },
      { w: "punctual", p: "a.", zh: "准时的", ex: "Please be punctual for the client call." },
      { w: "attendance", p: "n.", zh: "出席（人数）", ex: "Attendance doubled this year." },
      { w: "in person", p: "phr.", zh: "亲自；当面", ex: "Attend the hearing in person." }
    ]
  },
  {
    id: "comm", name: "通讯联络", icon: "☎️",
    words: [
      { w: "dial", p: "v.", zh: "拨（号）", ex: "Dial 9 for an outside line." },
      { w: "hang up", p: "phr.", zh: "挂断电话", ex: "Don't hang up; I'll transfer you." },
      { w: "put through", p: "phr.", zh: "接通（电话）", ex: "I'll put you through to sales." },
      { w: "hold the line", p: "phr.", zh: "别挂断；稍等", ex: "Please hold the line a moment." },
      { w: "signal", p: "n.", zh: "信号", ex: "There's no signal in the tunnel." },
      { w: "voicemail", p: "n.", zh: "语音留言", ex: "Leave a voicemail if I don't answer." },
      { w: "disconnect", p: "v.", zh: "断开；挂断", ex: "We got disconnected twice." },
      { w: "unreachable", p: "a.", zh: "联系不上的", ex: "The client was unreachable all morning." },
      { w: "area code", p: "phr.", zh: "区号", ex: "Tokyo's area code is 03." },
      { w: "operator", p: "n.", zh: "接线员", ex: "Dial zero for the operator." },
      { w: "callback", p: "n.", zh: "回电", ex: "I'll give him a callback at two." },
      { w: "busy signal", p: "phr.", zh: "占线音", ex: "I keep getting a busy signal." },
      { w: "speakerphone", p: "n.", zh: "免提电话", ex: "Let's use the speakerphone for the call." },
      { w: "mute", p: "v./n.", zh: "静音", ex: "Please mute yourself when not speaking." },
      { w: "conference call", p: "phr.", zh: "电话会议", ex: "Join the conference call by ten." },
      { w: "redial", p: "v.", zh: "重拨", ex: "Redial if the call drops." },
      { w: "leave a message", p: "phr.", zh: "留言", ex: "Would you like to leave a message?" },
      { w: "pick up", p: "phr.", zh: "接（电话）", ex: "He never picks up before nine." },
      { w: "get cut off", p: "phr.", zh: "（通话）被中断", ex: "We got cut off in the elevator." },
      { w: "reception", p: "n.", zh: "（手机）信号；接待", ex: "I have poor reception in the basement." }
    ]
  },
  {
    id: "education", name: "教育培训", icon: "🎓",
    words: [
      { w: "curriculum", p: "n.", zh: "课程体系", ex: "The curriculum was updated this year." },
      { w: "lecture", p: "n.", zh: "讲座；授课", ex: "The lecture starts at two sharp." },
      { w: "enrollment", p: "n.", zh: "注册；入学人数", ex: "Enrollment ends on Sunday." },
      { w: "tuition", p: "n.", zh: "学费", ex: "The company covers tuition for MBA courses." },
      { w: "semester", p: "n.", zh: "学期", ex: "The new semester begins in April." },
      { w: "textbook", p: "n.", zh: "教科书", ex: "Buy the textbook before the first class." },
      { w: "handout", p: "n.", zh: "讲义；宣传单", ex: "Handouts are available at the door." },
      { w: "quiz", p: "n.", zh: "小测验", ex: "There's a short quiz every Friday." },
      { w: "instructor", p: "n.", zh: "讲师；教员", ex: "Ask the instructor for feedback." },
      { w: "certificate", p: "n.", zh: "证书", ex: "You'll get a certificate of completion." },
      { w: "seminar", p: "n.", zh: "研讨会", ex: "Register early; the seminar fills fast." },
      { w: "session", p: "n.", zh: "一场（课/会议）", ex: "Each session lasts ninety minutes." },
      { w: "attendee", p: "n.", zh: "出席者", ex: "All attendees receive a free booklet." },
      { w: "register", p: "v.", zh: "报名；登记", ex: "Register online to reserve a seat." },
      { w: "syllabus", p: "n.", zh: "教学大纲", ex: "The syllabus lists all assignments." },
      { w: "mentor", p: "n.", zh: "导师", ex: "Each intern is paired with a mentor." },
      { w: "internship", p: "n.", zh: "实习", ex: "She completed a summer internship." },
      { w: "knowledgeable", p: "a.", zh: "知识渊博的", ex: "The staff are knowledgeable and friendly." },
      { w: "tutoring", p: "n.", zh: "辅导", ex: "Free English tutoring is offered Tuesdays." },
      { w: "degree", p: "n.", zh: "学位", ex: "Applicants need a business degree." }
    ]
  },
  {
    id: "media", name: "媒体出版", icon: "📰",
    words: [
      { w: "broadcast", p: "v./n.", zh: "广播；播出", ex: "The interview will be broadcast live." },
      { w: "headline", p: "n.", zh: "标题；头条", ex: "The story made national headlines." },
      { w: "press release", p: "phr.", zh: "新闻稿", ex: "The company issued a press release." },
      { w: "coverage", p: "n.", zh: "报道；覆盖范围", ex: "The event got full media coverage." },
      { w: "journalist", p: "n.", zh: "记者", ex: "Journalists were invited to the launch." },
      { w: "edition", p: "n.", zh: "版本；（报刊）期", ex: "Read the story in tomorrow's edition." },
      { w: "issue", p: "n.", zh: "（报刊）期；问题", ex: "The June issue sold out quickly." },
      { w: "column", p: "n.", zh: "专栏", ex: "She writes a weekly money column." },
      { w: "feature", p: "n./v.", zh: "特写；以…为特色", ex: "The magazine features local startups." },
      { w: "article", p: "n.", zh: "文章", ex: "Your article is due Thursday." },
      { w: "circulation", p: "n.", zh: "发行量", ex: "The paper's circulation is falling." },
      { w: "publish", p: "v.", zh: "出版；发表", ex: "The results were published online." },
      { w: "editor", p: "n.", zh: "编辑", ex: "Send the draft to your editor." },
      { w: "reporter", p: "n.", zh: "记者；报道员", ex: "A reporter toured the new plant." },
      { w: "exclusive", p: "n./a.", zh: "独家报道；独有的", ex: "We have an exclusive interview." },
      { w: "press conference", p: "phr.", zh: "记者会", ex: "The CEO held a press conference." },
      { w: "documentary", p: "n.", zh: "纪录片", ex: "The documentary airs next month." },
      { w: "weekly", p: "a./adv.", zh: "每周的", ex: "The weekly bulletin lists openings." },
      { w: "columnist", p: "n.", zh: "专栏作家", ex: "A guest columnist wrote today's piece." },
      { w: "on air", p: "phr.", zh: "正在播出", ex: "The station is on air all night." }
    ]
  },
  {
    id: "directions", name: "方位指引", icon: "🧭",
    words: [
      { w: "intersection", p: "n.", zh: "十字路口", ex: "Turn right at the second intersection." },
      { w: "crosswalk", p: "n.", zh: "人行横道", ex: "Use the crosswalk to cross safely." },
      { w: "pedestrian", p: "n.", zh: "行人", ex: "The bridge is for pedestrians only." },
      { w: "avenue", p: "n.", zh: "大街；大道", ex: "The office is on Maple Avenue." },
      { w: "block", p: "n.", zh: "街区", ex: "It's three blocks from the station." },
      { w: "corner", p: "n.", zh: "拐角", ex: "The pharmacy is on the corner." },
      { w: "opposite", p: "a./prep.", zh: "对面的", ex: "The café is opposite the bank." },
      { w: "adjacent", p: "a.", zh: "毗邻的", ex: "The parking lot is adjacent to the hotel." },
      { w: "downstairs", p: "adv.", zh: "楼下", ex: "The cafeteria is downstairs." },
      { w: "upstairs", p: "adv.", zh: "楼上", ex: "HR has moved upstairs." },
      { w: "basement", p: "n.", zh: "地下室", ex: "Storage is in the basement." },
      { w: "rear", p: "n./a.", zh: "后面；后部的", ex: "Enter through the rear entrance." },
      { w: "around the corner", p: "phr.", zh: "在附近；拐角处", ex: "The bus stop is around the corner." },
      { w: "straight ahead", p: "phr.", zh: "一直向前", ex: "Go straight ahead for two blocks." },
      { w: "make a left", p: "phr.", zh: "向左转", ex: "Make a left at the light." },
      { w: "detour", p: "n.", zh: "绕行路线", ex: "There's a detour around the bridge." },
      { w: "one-way street", p: "phr.", zh: "单行道", ex: "This is a one-way street." },
      { w: "vicinity", p: "n.", zh: "附近一带", ex: "No parking in the vicinity of the gate." },
      { w: "escalator", p: "n.", zh: "自动扶梯", ex: "Take the escalator to level two." },
      { w: "main entrance", p: "phr.", zh: "正门；主入口", ex: "Meet at the main entrance at nine." }
    ]
  },
  {
    id: "job", name: "求职招聘", icon: "💼",
    words: [
      { w: "opening", p: "n.", zh: "空缺岗位", ex: "There's an opening in the design team." },
      { w: "apply", p: "v.", zh: "申请", ex: "Apply by May 31 through our website." },
      { w: "application", p: "n.", zh: "申请；申请书", ex: "Your application was received." },
      { w: "qualification", p: "n.", zh: "资格；资历", ex: "List your qualifications on the form." },
      { w: "requirement", p: "n.", zh: "要求；必备条件", ex: "Japanese is a basic requirement." },
      { w: "candidate", p: "n.", zh: "候选人", ex: "We interviewed five candidates." },
      { w: "cover letter", p: "phr.", zh: "求职信", ex: "Attach a cover letter to your resume." },
      { w: "entry-level", p: "a.", zh: "初级水平的", ex: "It's an entry-level position." },
      { w: "experienced", p: "a.", zh: "有经验的", ex: "We seek experienced engineers." },
      { w: "full-time", p: "a.", zh: "全职的", ex: "The role is full-time, on-site." },
      { w: "part-time", p: "a.", zh: "兼职的", ex: "Part-time staff get pro-rated benefits." },
      { w: "position", p: "n.", zh: "职位", ex: "The position is based in Osaka." },
      { w: "job offer", p: "phr.", zh: "录用通知", ex: "She accepted the job offer." },
      { w: "compensation", p: "n.", zh: "薪酬；补偿", ex: "Compensation is competitive." },
      { w: "career fair", p: "phr.", zh: "招聘会", ex: "Visit our booth at the career fair." },
      { w: "hands-on", p: "a.", zh: "实际动手的", ex: "The course includes hands-on training." },
      { w: "potential", p: "n./a.", zh: "潜力；潜在的", ex: "We hire for potential, not just skills." },
      { w: "ambitious", p: "a.", zh: "有雄心的", ex: "An ambitious team is growing fast." },
      { w: "specialized", p: "a.", zh: "专门的；专业化的", ex: "Specialized training is provided." },
      { w: "unemployed", p: "a.", zh: "失业的", ex: "He was unemployed for three months." }
    ]
  },
  {
    id: "speaking", name: "演讲表达", icon: "🎤",
    words: [
      { w: "outline", p: "n./v.", zh: "大纲；概述", ex: "Here's a quick outline of my talk." },
      { w: "briefly", p: "adv.", zh: "简短地", ex: "I'll briefly explain the process." },
      { w: "summarize", p: "v.", zh: "总结；概述", ex: "To summarize, sales are up 8%." },
      { w: "visual aid", p: "phr.", zh: "视觉辅助教具", ex: "Use visual aids to keep attention." },
      { w: "pointer", p: "n.", zh: "指示笔；提示", ex: "She used a laser pointer." },
      { w: "audience", p: "n.", zh: "观众；听众", ex: "Know your audience before you speak." },
      { w: "applause", p: "n.", zh: "掌声", ex: "The talk ended with loud applause." },
      { w: "introduction", p: "n.", zh: "引言；介绍", ex: "Skip the long introduction." },
      { w: "conclusion", p: "n.", zh: "结论；结尾", ex: "In conclusion, we recommend option B." },
      { w: "emphasize", p: "v.", zh: "强调", ex: "I'd like to emphasize three points." },
      { w: "highlight", p: "v./n.", zh: "突出；亮点", ex: "Let me highlight the key figures." },
      { w: "elaborate", p: "v.", zh: "详细说明", ex: "Could you elaborate on that?" },
      { w: "demonstrate", p: "v.", zh: "演示；证明", ex: "The video demonstrates the process." },
      { w: "point out", p: "phr.", zh: "指出", ex: "He pointed out a scheduling conflict." },
      { w: "gesture", p: "n.", zh: "手势", ex: "Use natural gestures while speaking." },
      { w: "eye contact", p: "phr.", zh: "眼神交流", ex: "Make eye contact with the room." },
      { w: "rehearse", p: "v.", zh: "排练；预演", ex: "Rehearse your presentation twice." },
      { w: "microphone", p: "n.", zh: "麦克风", ex: "Test the microphone before starting." },
      { w: "opening remarks", p: "phr.", zh: "开场白", ex: "The president gave the opening remarks." },
      { w: "Q&A session", p: "phr.", zh: "问答环节", ex: "A Q&A session follows the talk." }
    ]
  }
];
